# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Locations Client' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Locations Client
  pod 'Alamofire', '~> 5.0.0-beta.5'

  target 'Locations ClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Locations ClientUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
